# Generated by Django 3.0 on 2019-12-18 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_profile_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=models.CharField(default='None', max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
