# Generated by Django 3.0 on 2019-12-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191220_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemCategory',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Baby'), (2, 'Beverages'), (3, 'Bread and Bakery'), (4, 'Breakfast and Cereal'), (5, 'Canned Goods and Soups'), (6, 'Condiments/Spices and Bake'), (7, 'Cookies, Snacks and Candy'), (8, 'Diary, Eggs and Cheese'), (9, 'Frozen Foods'), (10, 'Produce: Fruits and Vegetables'), (11, 'Grains, Pasta and Sides'), (12, 'Miscellaneous'), (13, 'Paper Products'), (14, 'Cleaning Supplies'), (15, 'Cosmetics'), (16, 'Pet Care'), (17, 'Pharmacy')], max_length=100),
        ),
    ]
