# Generated by Django 3.0 on 2019-12-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191220_0555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='itemDetails',
            new_name='Details',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemDiscount',
            new_name='Discount',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemPrice',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemStock',
            new_name='Stock',
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemCategory',
        ),
        migrations.AddField(
            model_name='item',
            name='Category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Baby'), (2, 'Beverages'), (3, 'Bread and Bakery'), (4, 'Breakfast and Cereal'), (5, 'Canned Goods and Soups'), (6, 'Condiments/Spices and Bake'), (7, 'Cookies, Snacks and Candy'), (8, 'Diary, Eggs and Cheese'), (9, 'Frozen Foods'), (10, 'Produce: Fruits and Vegetables'), (11, 'Grains, Pasta and Sides'), (12, 'Miscellaneous'), (13, 'Paper Products'), (14, 'Cleaning Supplies'), (15, 'Cosmetics'), (16, 'Pet Care'), (17, 'Pharmacy')], default=1),
        ),
    ]
