# Generated by Django 3.0 on 2019-12-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20191220_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Image',
            field=models.ImageField(default='default.jpg', upload_to='item_pics'),
        ),
    ]
