# Generated by Django 3.0 on 2019-12-21 04:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Price',
            field=models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
