# Generated by Django 3.0 on 2019-12-21 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0006_auto_20191221_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apartment', models.CharField(max_length=100)),
                ('Street', models.CharField(max_length=100)),
                ('Zip', models.CharField(max_length=6)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='Slug',
            field=models.SlugField(default=models.CharField(max_length=100)),
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ordered', models.BooleanField(default=False)),
                ('Quantity', models.PositiveIntegerField(default=1)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Item')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateTimeField(auto_now_add=True)),
                ('OrderDate', models.DateTimeField()),
                ('Ordered', models.BooleanField(default=False)),
                ('Payment', models.PositiveSmallIntegerField(choices=[(1, 'Cash on Delivery'), (2, 'Card Payment on Delivery')], default=1)),
                ('Delivered', models.BooleanField(default=False)),
                ('Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Address')),
                ('Items', models.ManyToManyField(to='shop.Order_Item')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
