# Generated by Django 3.0 on 2019-12-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20191221_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Ordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='StartDate',
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
