# Generated by Django 3.0 on 2019-12-23 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20191223_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrderDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
